---
title: "MZCCS Annotation Tool"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(data.table)
library(DT)
library(enviGCMS)
```

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r}
fileInput("database", "Upload Database CSV", accept = ".csv")
fileInput("reference", "Upload Reference CSV", accept = ".csv")

selectInput("ion_mode", "Ion Mode",
            choices = c("Positive" = "positive", "Negative" = "negative"),
            selected = "positive")

numericInput("mz_ppmshift", "M/Z PPM Shift", value = 20, min = 0)
numericInput("ccs_shift", "CCS Shift", value = 5, min = 0)

actionButton("run_analysis", "Run Analysis")

downloadButton("download_results", "Download Results")
```

Results
-----------------------------------------------------------------------

### Annotation Results

```{r}
output$results_table <- DT::renderDataTable({
  req(input$run_analysis)
  
  # Load database
  lipid <- fread(input$database$datapath)
  
  # Set ion mode
  if (input$ion_mode == "positive") {
    lipid <- lipid[adducts %in% c('[M+H]','[M+Na]','[M+NH4]','[M+H-H2O]','[M+]','[M+K]')]
  } else {
    lipid <- lipid[adducts %in% c('[M-H]','[M+Cl]','[M-H+FA]','[M-]','[M+Na-2H]')]
  }
  
  # Load ref peaks
  ref <- fread(input$reference$datapath)
  mz <- ref$mz
  im <- ref$im
  
  # Align
  align <- enviGCMS::getalign(mz, lipid$mz, im, lipid$ccs, 
                              ppm = input$mz_ppmshift, deltart = input$ccs_shift)
  
  anno <- cbind.data.frame(mz = mz[align$xid], im = im[align$xid],
                           db_mz = align$mz2, db_im = align$rt2)
  
  lipidanno <- merge(anno, lipid, by.x = c('db_mz','db_im'), by.y = c('mz','ccs'))
  lipidanno <- lipidanno[!duplicated(lipidanno),]
  
  # Save results for download
  results <<- lipidanno
  
  # Return results for display
  DT::datatable(lipidanno, options = list(pageLength = 10))
})

DT::dataTableOutput("results_table")
```

```{r}
output$download_results <- downloadHandler(
  filename = function() {
    paste("mzccs_annotation_results_", Sys.Date(), ".csv", sep = "")
  },
  content = function(file) {
    fwrite(results, file)
  }
)
```
