---
title: "Visualization"
author: "Miao Yu"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval=FALSE,cache = TRUE,message=TRUE,warning=FALSE)
```

## Demo data

We prepared 5 NIST 1950 samples and 5 matrix blank samples as demodata.

```{r}
library(rmwf)
# Download demo data from figshare
library(rfigshare)
dir.create(file.path('data'), showWarnings = FALSE)
setwd(file.path('data'))
# NIST1950 postive data
dir.create(file.path('NIST1950'), showWarnings = FALSE)
setwd(file.path('NIST1950'))
article_id <- 13252196
details <- fs_details(article_id, mine = FALSE, session = NULL)
name <- sapply(details$files,function(x) x$name)
url <- sapply(details$files,function(x) x$download_url)
download.file(url, name)
setwd('..')
# matrix positive data
dir.create(file.path('Matrix'), showWarnings = FALSE)
setwd(file.path('Matrix'))
article_id <- 13252244
details <- fs_details(article_id, mine = FALSE, session = NULL)
name <- sapply(details$files,function(x) x$name)
url <- sapply(details$files,function(x) x$download_url)
download.file(url, name)
setwd('..')
path <- getwd()
files <- list.files(path,pattern = '*.mzML',recursive = T,full.names = T)
basename <- basename(path)
group <- xcms:::phenoDataFromPaths(files)$class
meta <- cbind.data.frame(name=basename,factor=group)
```

## EIC for xcms

Extracted ion chromatogram for xcms object.

### xcmsSet object

```{r}
library(xcms)
# you could load you eic and xset object, here is the demo data
data("srmeic")
data("srmxset")
# EIC for m/z 100 and retention time 38s
plot(srmeic,srmxset,groupidx = 'M100T38')
```

### XCMSnExp object

```{r}
# data visualization for xcms 3 object
files <- list.files(path,pattern = ".CDF|.mzXML|.mzML",full.names = T,recursive = T)
group <- xcms:::phenoDataFromPaths(files)
  if(NCOL(group)==1){
      sample_group <- group$class
  }else{
      cols <- colnames(group)
      sample_group <-  do.call(paste,c(group[cols],sep='_'))
  }
sample_name=sub(basename(files),pattern = ".CDF|.mzXML|.mzML",replacement = '')
pd <- data.frame(sample_name, sample_group,stringsAsFactors = F)
raw_data <- MSnbase::readMSData(files = files, pdata = new("NAnnotatedDataFrame", pd),
                       mode = "onDisk")
## Get the base peak chromatograms. This reads data from the files.
bpis <- xcms::chromatogram(raw_data, aggregationFun = "max")
## Define colors for the two groups
group_colors <- paste0(RColorBrewer::brewer.pal(3, "Set1")[1:2], "60")
names(group_colors) <- c("Nist 1950", "Matrix")
## Plot all chromatograms.
plot(bpis, col = group_colors[raw_data$sample_group])
## quick vis
tc <- split(tic(raw_data), f = fromFile(raw_data))
boxplot(tc, col = group_colors[raw_data$sample_group],
        ylab = "intensity", main = "Total ion current")
bic <- split(bpi(raw_data), f = fromFile(raw_data))
boxplot(bic, col = group_colors[raw_data$sample_group],
        ylab = "intensity", main = "Base peak ion current")
## EIC
## Define the rt and m/z range of the peak area
rtr <- c(200, 900)
mzr <- c(334.9, 335.1)
## extract the chromatogram
chr_raw <- chromatogram(raw_data, mz = mzr, rt = rtr)
plot(chr_raw, col = group_colors[chr_raw$sample_group])
data(para)
# remove co-elution and column wash phase
filter_data <- filterRt(raw_data,rt = c(100,800))
cwp <- CentWaveParam(peakwidth = c(para$min_peakwidth,para$max_peakwidth), 
                       ppm             = para$ppm,
                       noise           = para$noise,
                       snthresh        = para$snthresh,
                       mzdiff          = para$mzdiff,
                       prefilter       = c(para$prefilter,para$value_of_prefilter),
                       mzCenterFun     = para$mzCenterFun,
                       integrate       = para$integrate,
                       fitgauss        = para$fitgauss,
                       verboseColumns  = para$verbose.columns)
owp <- ObiwarpParam(binSize        = para$profStep,
                      centerSample = para$center,
                      response       = para$response,
                      distFun        = para$distFunc,
                      gapInit        = para$gapInit,
                      gapExtend      = para$gapExtend,
                      factorDiag     = para$factorDiag,
                      factorGap      = para$factorGap,
                      localAlignment = ifelse(para$localAlignment==0,F,T))
pdp <- PeakDensityParam(sampleGroups = pd$sample_group,
                        bw      = para$bw,
                        minFraction = para$minfrac,
                        minSamples = para$minsamp,
                        maxFeatures = para$max,
                        binSize = para$mzwid)

xdata <- findChromPeaks(filter_data, param = cwp)
xdata <- adjustRtime(xdata, param = owp)
xdata <- groupChromPeaks(xdata, param = pdp)
MSnbase::setMSnbaseFastLoad(FALSE)
xdata <- fillChromPeaks(xdata)

## check figure
plotChromPeaks(xdata, file = 3)
plotChromPeaks(xdata, file = 10)
plotChromPeakImage(xdata)
## check eic figure
plot(chr_raw, col = group_colors[chr_raw$sample_group], lwd = 2)
highlightChromPeaks(xdata, col = group_colors[chr_raw$sample_group],
                    lty = 3, rt = rtr, mz = mzr, border = NA,
                    type = "polygon")
## check peak shift
ints <- split(log2(chromPeaks(xdata)[, "into"]),
              f = chromPeaks(xdata)[, "sample"])
boxplot(ints, varwidth = TRUE, col = group_colors[xdata$sample_group],
        ylab = expression(log[2]~intensity), main = "Peak intensities")
grid(nx = NA, ny = NULL)
## Plot also the difference of adjusted to raw retention time.
plotAdjustedRtime(xdata, col = group_colors[xdata$sample_group])
```

## Peaks list

Here we list some common visualization method for peaks list.

```{r}
# PCA
enviGCMS::plotpca(data = mzrt$data,lv = mzrt$group$sample_group)
# MDS
library(MASS)
d <- dist(t(mzrt$data)) # euclidean distances between the rows
fit <- isoMDS(d, k=3) # k is the number of dim
fit # view results
x <- fit$points[,1]
y <- fit$points[,2]
plot(x, y, xlab="Coordinate 1", ylab="Coordinate 2",
     main="Metric MDS", type="n")
text(x, y, cex=.7) 
# mzrt plot
enviGCMS::plotmr(mzrt)
# RSD plot
enviGCMS::plotrsd(mzrt)
# mean rsd analysis
library(tidyverse)
a <- cbind.data.frame(NISTmean = gm[,1],NISTrsd = gr[,1])
p <- ggplot(a,aes(x=log10(NISTmean),y=NISTrsd)) +
        ggtitle("Mean vs. RSD%") +
        xlab("log10(Mean)") +
        ylab("rsd%") 
# Visualization 1 for density plot
p1 <-  p + 
  geom_point(alpha = 0.5, colour="orange")+
        geom_density2d()
p1
# Visualization 2 for grdient
p2 <- p +
  stat_bin_hex(colour="white", na.rm=TRUE) +
  scale_fill_gradientn(colours=c("red","orange"), name = "Frequency", na.value=NA)
p2
# Visualization 3 for smooth scatter
smoothScatter(x=log10(a$NISTmean),y=a$NISTrsd)
# density plot
enviGCMS::plotden(mzrt$data,lv=mzrt$group$sample_group,ylim = c(0,1))
# heatmap
enviGCMS::plothm(mzrt$data,lv=factor(mzrt$group$sample_group),index = c(1:20))
# TSNE
# rtsne_out <- Rtsne::Rtsne(t(mzrtfilter$data))
# plot(rtsne_out)
# visulize the batch effect/run order effects
enviGCMS::plotrla(mzrt$data,lv = as.factor(mzrt$group$sample_group))
enviGCMS::plotridges(mzrt$data,lv = factor(mzrt$group$sample_group))
```

```{r}
sessionInfo()
```

